/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2026-04-09 21:23:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Rodado;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.sample.core.domain.Rodado;

public final class editarRodado_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.sample.core.domain.Rodado");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    // Recuperamos el objeto que el Servlet envió en el request
    Rodado rodado = (Rodado) request.getAttribute("rodado");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Editar Rodado - Panel de Gestión</title>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Bootstrap 5.3 -->\r\n");
      out.write("    <link href=\"https://jsdelivr.net\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cloudflare.com\">\r\n");
      out.write("    <!-- Google Fonts: Poppins -->\r\n");
      out.write("    <link href=\"https://googleapis.com\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        :root { --primary-color: #4361ee; --bg-body: #f4f7fe; }\r\n");
      out.write("        body { font-family: 'Poppins', sans-serif; background-color: var(--bg-body); color: #2b3674; }\r\n");
      out.write("        .form-card { background: white; border: none; border-radius: 20px; box-shadow: 0 10px 30px rgba(0,0,0,0.08); overflow: hidden; }\r\n");
      out.write("        .form-header { background: var(--primary-color); color: white; padding: 2rem; text-align: center; }\r\n");
      out.write("        .form-body { padding: 2.5rem; }\r\n");
      out.write("        .form-label { font-weight: 600; font-size: 0.85rem; color: #4a5568; margin-bottom: 0.5rem; }\r\n");
      out.write("        .form-control, .form-select { border-radius: 12px; padding: 0.75rem 1rem; border: 2px solid #edf2f7; }\r\n");
      out.write("        .input-group-text { background: #f8fafc; border: 2px solid #edf2f7; border-right: none; border-radius: 12px 0 0 12px; color: #a0aec0; }\r\n");
      out.write("        .btn-save { background: var(--primary-color); border: none; border-radius: 12px; padding: 12px; font-weight: 600; width: 100%; color: white; margin-top: 1.5rem; transition: 0.3s; }\r\n");
      out.write("        .btn-back { color: #718096; text-decoration: none; font-size: 0.9rem; display: inline-flex; align-items: center; margin-bottom: 1.5rem; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container py-5\">\r\n");
      out.write("    <div class=\"row justify-content-center\">\r\n");
      out.write("        <div class=\"col-lg-8\">\r\n");
      out.write("            \r\n");
      out.write("            <a href=\"listarRodado\" class=\"btn-back\">\r\n");
      out.write("                <i class=\"fa-solid fa-arrow-left me-2\"></i> Volver al listado\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-card\">\r\n");
      out.write("                <div class=\"form-header\">\r\n");
      out.write("                    <i class=\"fa-solid fa-car-side fa-3x mb-3\"></i>\r\n");
      out.write("                    <h2 class=\"fw-bold mb-0\">Editar Vehículo</h2>\r\n");
      out.write("                    <p class=\"mb-0 opacity-75\">Actualizando datos de la patente: ");
      out.print( rodado.getPatente() );
      out.write("</p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-body\">\r\n");
      out.write("                    <form action=\"");
      out.print( request.getContextPath() );
      out.write("/actualizarRodado\" method=\"post\">\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <!-- Patente (ReadOnly) -->\r\n");
      out.write("                            <div class=\"col-md-6 mb-4\">\r\n");
      out.write("                                <label for=\"patente\" class=\"form-label\">Patente</label>\r\n");
      out.write("                                <div class=\"input-group\">\r\n");
      out.write("                                    <span class=\"input-group-text\"><i class=\"fa-solid fa-id-card\"></i></span>\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control bg-light\" id=\"patente\" name=\"patente\" \r\n");
      out.write("                                           value=\"");
      out.print( rodado.getPatente() );
      out.write("\" readonly>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Chasis -->\r\n");
      out.write("                            <div class=\"col-md-6 mb-4\">\r\n");
      out.write("                                <label for=\"chasis\" class=\"form-label\">Número de Chasis</label>\r\n");
      out.write("                                <div class=\"input-group\">\r\n");
      out.write("                                    <span class=\"input-group-text\"><i class=\"fa-solid fa-barcode\"></i></span>\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" id=\"chasis\" name=\"chasis\" \r\n");
      out.write("                                           value=\"");
      out.print( rodado.getChasis() );
      out.write("\" required>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Color -->\r\n");
      out.write("                            <div class=\"col-md-4 mb-4\">\r\n");
      out.write("                                <label for=\"color\" class=\"form-label\">Color</label>\r\n");
      out.write("                                <div class=\"input-group\">\r\n");
      out.write("                                    <span class=\"input-group-text\"><i class=\"fa-solid fa-palette\"></i></span>\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" id=\"color\" name=\"color\" \r\n");
      out.write("                                           value=\"");
      out.print( rodado.getColor() );
      out.write("\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Caja -->\r\n");
      out.write("                            <div class=\"col-md-4 mb-4\">\r\n");
      out.write("                                <label for=\"caja\" class=\"form-label\">Tipo de Caja</label>\r\n");
      out.write("                                <select class=\"form-select\" id=\"caja\" name=\"caja\">\r\n");
      out.write("                                    <option value=\"MANUAL\" ");
      out.print( rodado.getCaja().name().equals("MANUAL") ? "selected" : "" );
      out.write(">Manual</option>\r\n");
      out.write("                                    <option value=\"AUTOMATICO\" ");
      out.print( rodado.getCaja().name().equals("AUTOMATICO") ? "selected" : "" );
      out.write(">Automática</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Motor -->\r\n");
      out.write("                            <div class=\"col-md-4 mb-4\">\r\n");
      out.write("                                <label for=\"motor\" class=\"form-label\">Motor</label>\r\n");
      out.write("                                <select class=\"form-select\" id=\"motor\" name=\"motor\">\r\n");
      out.write("                                    <option value=\"DIESEL\" ");
      out.print( rodado.getMotor().name().equals("DIESEL") ? "selected" : "" );
      out.write(">Diesel</option>\r\n");
      out.write("                                    <option value=\"HIBRIDO\" ");
      out.print( rodado.getMotor().name().equals("HIBRIDO") ? "selected" : "" );
      out.write(">Híbrido</option>\r\n");
      out.write("                                    <option value=\"ELECTRICO\" ");
      out.print( rodado.getMotor().name().equals("ELECTRICO") ? "selected" : "" );
      out.write(">Eléctrico</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Estado -->\r\n");
      out.write("                            <div class=\"col-md-4 mb-4\">\r\n");
      out.write("                                <label for=\"tipoEstado\" class=\"form-label\">Estado</label>\r\n");
      out.write("                                <select class=\"form-select\" id=\"tipoEstado\" name=\"tipoEstado\">\r\n");
      out.write("                                    <option value=\"NUEVO\" ");
      out.print( rodado.getTipoEstado().name().equals("NUEVO") ? "selected" : "" );
      out.write(">Nuevo</option>\r\n");
      out.write("                                    <option value=\"USADO\" ");
      out.print( rodado.getTipoEstado().name().equals("USADO") ? "selected" : "" );
      out.write(">Usado</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Consumo -->\r\n");
      out.write("                            <div class=\"col-md-4 mb-4\">\r\n");
      out.write("                                <label for=\"tipoConsumo\" class=\"form-label\">Consumo</label>\r\n");
      out.write("                                <select class=\"form-select\" id=\"tipoConsumo\" name=\"tipoConsumo\">\r\n");
      out.write("                                    <option value=\"BAJO\" ");
      out.print( rodado.getTipoConsumo().name().equals("BAJO") ? "selected" : "" );
      out.write(">Bajo</option>\r\n");
      out.write("                                    <option value=\"MEDIO\" ");
      out.print( rodado.getTipoConsumo().name().equals("MEDIO") ? "selected" : "" );
      out.write(">Medio</option>\r\n");
      out.write("                                    <option value=\"ALTO\" ");
      out.print( rodado.getTipoConsumo().name().equals("ALTO") ? "selected" : "" );
      out.write(">Alto</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Puertas -->\r\n");
      out.write("                            <div class=\"col-md-4 mb-4\">\r\n");
      out.write("                                <label for=\"puertas\" class=\"form-label\">Puertas</label>\r\n");
      out.write("                                <select class=\"form-select\" id=\"puertas\" name=\"puertas\">\r\n");
      out.write("                                    <option value=\"DOS\" ");
      out.print( rodado.getPuertas().name().equals("DOS") ? "selected" : "" );
      out.write(">2 Puertas</option>\r\n");
      out.write("                                    <option value=\"CUATRO\" ");
      out.print( rodado.getPuertas().name().equals("CUATRO") ? "selected" : "" );
      out.write(">4 Puertas</option>\r\n");
      out.write("                                    <option value=\"CINCO\" ");
      out.print( rodado.getPuertas().name().equals("CINCO") ? "selected" : "" );
      out.write(">5 Puertas</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Tipo Rodado -->\r\n");
      out.write("                            <div class=\"col-md-12 mb-4\">\r\n");
      out.write("                                <label for=\"tipoRodado\" class=\"form-label\">Tipo de Rodado</label>\r\n");
      out.write("                                <select class=\"form-select\" id=\"tipoRodado\" name=\"tipoRodado\">\r\n");
      out.write("                                    <option value=\"AUTO\" ");
      out.print( rodado.getTipoRodado().name().equals("AUTO") ? "selected" : "" );
      out.write(">Auto</option>\r\n");
      out.write("                                    <option value=\"MOTO\" ");
      out.print( rodado.getTipoRodado().name().equals("MOTO") ? "selected" : "" );
      out.write(">Moto</option>\r\n");
      out.write("                                    <option value=\"CAMIONETA\" ");
      out.print( rodado.getTipoRodado().name().equals("CAMIONETA") ? "selected" : "" );
      out.write(">Camioneta</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-save\">\r\n");
      out.write("                            <i class=\"fa-solid fa-floppy-disk me-2\"></i> Guardar Cambios\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
