/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2026-04-12 23:30:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Rodado;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.sample.core.domain.Rodado;

public final class listarRodado_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.sample.core.domain.Rodado");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Panel de Control - Flota de Rodados</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap 5.3 -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Font Awesome para íconos -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com\">\r\n");
      out.write("<!-- Google Fonts: Poppins -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(":root {\r\n");
      out.write("\t--primary-color: #4361ee;\r\n");
      out.write("\t--secondary-color: #3f37c9;\r\n");
      out.write("\t--bg-body: #f4f7fe;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: 'Poppins', sans-serif;\r\n");
      out.write("\tbackground-color: var(--bg-body);\r\n");
      out.write("\tcolor: #2b3674;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main-card {\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tborder-radius: 20px;\r\n");
      out.write("\tbox-shadow: 0 10px 30px rgba(0, 0, 0, 0.05);\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\tpadding: 2rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table {\r\n");
      out.write("\tborder-collapse: separate;\r\n");
      out.write("\tborder-spacing: 0 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table thead th {\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tcolor: #a3aed0;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("\tfont-size: 0.75rem;\r\n");
      out.write("\tletter-spacing: 1px;\r\n");
      out.write("\tpadding-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table tbody tr {\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\tbox-shadow: 0 5px 10px rgba(0, 0, 0, 0.02);\r\n");
      out.write("\tborder-radius: 12px;\r\n");
      out.write("\ttransition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table tbody tr:hover {\r\n");
      out.write("\ttransform: scale(1.01);\r\n");
      out.write("\tbox-shadow: 0 8px 15px rgba(0, 0, 0, 0.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table td {\r\n");
      out.write("\tpadding: 1.5rem 1rem;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".patente-cell {\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\tcolor: var(--primary-color);\r\n");
      out.write("\tbackground: #eef2ff;\r\n");
      out.write("\tpadding: 8px 12px;\r\n");
      out.write("\tborder-radius: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-add {\r\n");
      out.write("\tbackground: var(--primary-color);\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tborder-radius: 12px;\r\n");
      out.write("\tpadding: 10px 24px;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\ttransition: 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-add:hover {\r\n");
      out.write("\tbackground: var(--secondary-color);\r\n");
      out.write("\tbox-shadow: 0 4px 15px rgba(67, 97, 238, 0.4);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".badge-status {\r\n");
      out.write("\tpadding: 8px 12px;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\tfont-size: 0.75rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".action-icon {\r\n");
      out.write("\twidth: 35px;\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("\tdisplay: inline-flex;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\ttransition: 0.2s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon-edit {\r\n");
      out.write("\tbackground: #fff4e5;\r\n");
      out.write("\tcolor: #ffab00;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon-delete {\r\n");
      out.write("\tbackground: #ffe5e5;\r\n");
      out.write("\tcolor: #ff5b5c;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon-edit:hover {\r\n");
      out.write("\tbackground: #ffab00;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon-delete:hover {\r\n");
      out.write("\tbackground: #ff5b5c;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".empty-state {\r\n");
      out.write("\tpadding: 60px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container py-5\">\r\n");
      out.write("\t\t<!-- Header -->\r\n");
      out.write("\t\t<div class=\"d-flex justify-content-between align-items-center mb-5\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<h1 class=\"fw-bold h2 mb-1 text-dark\">Flota de Vehículos</h1>\r\n");
      out.write("\t\t\t\t<nav aria-label=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t\t<ol class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"breadcrumb-item\"><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"text-decoration-none\">Dashboard</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"breadcrumb-item active\">Rodados</li>\r\n");
      out.write("\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/Rodado/rodadoForm.jsp\"\r\n");
      out.write("\t\t\t\tclass=\"btn btn-primary btn-add\"> <i\r\n");
      out.write("\t\t\t\tclass=\"fa-solid fa-plus me-2\"></i> Nuevo Rodado\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Main Table Card -->\r\n");
      out.write("\t\t<div class=\"main-card\">\r\n");
      out.write("\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t<table class=\"table align-middle\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Vehículo</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Chasis / Color</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Especificaciones</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Estado</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Categoría</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"text-end\">Acciones</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("    ");

    List<Rodado> lista = (List<Rodado>) request.getAttribute("listaRodados");
    if (lista != null && !lista.isEmpty()) {
        for (Rodado r : lista) {
    
      out.write("\r\n");
      out.write("    <tr id=\"fila-");
      out.print(r.getPatente());
      out.write("\">\r\n");
      out.write("        <td>\r\n");
      out.write("            <div class=\"d-flex align-items-center\">\r\n");
      out.write("                <span class=\"patente-cell me-3 text-uppercase\">");
      out.print(r.getPatente());
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("            <div class=\"small fw-bold\">Chasis: ");
      out.print(r.getChasis());
      out.write("</div>\r\n");
      out.write("            <div class=\"text-muted small\">\r\n");
      out.write("                <i class=\"fa-solid fa-palette me-1\"></i>");
      out.print(r.getColor());
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("            <div class=\"small mb-1\">\r\n");
      out.write("                <i class=\"fa-solid fa-gear text-muted me-1\"></i>");
      out.print(r.getCaja());
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"small\">\r\n");
      out.write("                <i class=\"fa-solid fa-gas-pump text-muted me-1\"></i>");
      out.print(r.getMotor());
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("            <span class=\"badge badge-status ");
      out.print(r.getTipoEstado().toString().equals("NUEVO") ? "bg-success-subtle text-success" : "bg-warning-subtle text-warning");
      out.write("\">\r\n");
      out.write("                <i class=\"fa-solid fa-circle fa-2xs me-1\"></i> ");
      out.print(r.getTipoEstado());
      out.write("\r\n");
      out.write("            </span>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("            <span class=\"fw-semibold small text-uppercase text-secondary\">\r\n");
      out.write("                <i class=\"fa-solid fa-car-side me-1\"></i> ");
      out.print(r.getTipoRodado());
      out.write("\r\n");
      out.write("            </span>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td class=\"text-end\">\r\n");
      out.write("            <!-- BOTÓN EDITAR -->\r\n");
      out.write("            <a href=\"actualizarRodado?patente=");
      out.print(r.getPatente());
      out.write("\" \r\n");
      out.write("               class=\"action-icon icon-edit me-2\" \r\n");
      out.write("               title=\"Editar\">\r\n");
      out.write("                <i class=\"fa-solid fa-pen-to-square\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("            \r\n");
      out.write("            <!-- BOTÓN ELIMINAR -->\r\n");
      out.write("            <a href=\"javascript:void(0)\" \r\n");
      out.write("               onclick=\"eliminarRodado('");
      out.print(r.getPatente());
      out.write("')\" \r\n");
      out.write("               class=\"action-icon icon-delete\" \r\n");
      out.write("               title=\"Eliminar\">\r\n");
      out.write("                <i class=\"fa-solid fa-trash\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    ");

        }
    } else {
    
      out.write("\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td colspan=\"6\">\r\n");
      out.write("            <div class=\"empty-state text-center py-5\">\r\n");
      out.write("                <i class=\"fa-solid fa-car-rear fa-4x text-light mb-3\"></i>\r\n");
      out.write("                <h5 class=\"text-muted\">No hay rodados registrados</h5>\r\n");
      out.write("                <p class=\"small text-muted\">Comienza agregando un nuevo vehículo al inventario.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    ");

    }
    
      out.write("\r\n");
      out.write("</tbody>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 3. POR ÚLTIMO tu archivo que USA a las librerías de arriba -->\r\n");
      out.write("    <script src=\"");
      out.print( request.getContextPath() );
      out.write("/assets/js/rodado.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
