/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2026-03-30 14:54:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Rodado;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class rodadoForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Nuevo Rodado - Panel de Gestión</title>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Bootstrap 5.3 -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com\">\r\n");
      out.write("    <!-- Google Fonts: Poppins -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --primary-color: #4361ee;\r\n");
      out.write("            --bg-body: #f4f7fe;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body { \r\n");
      out.write("            font-family: 'Poppins', sans-serif; \r\n");
      out.write("            background-color: var(--bg-body);\r\n");
      out.write("            color: #2b3674;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-card {\r\n");
      out.write("            background: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            box-shadow: 0 10px 30px rgba(0,0,0,0.08);\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-header {\r\n");
      out.write("            background: var(--primary-color);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-body {\r\n");
      out.write("            padding: 2.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-label {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            font-size: 0.85rem;\r\n");
      out.write("            color: #4a5568;\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-control, .form-select {\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            padding: 0.75rem 1rem;\r\n");
      out.write("            border: 2px solid #edf2f7;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-control:focus, .form-select:focus {\r\n");
      out.write("            border-color: var(--primary-color);\r\n");
      out.write("            box-shadow: 0 0 0 4px rgba(67, 97, 238, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .input-group-text {\r\n");
      out.write("            background: #f8fafc;\r\n");
      out.write("            border: 2px solid #edf2f7;\r\n");
      out.write("            border-right: none;\r\n");
      out.write("            border-radius: 12px 0 0 12px;\r\n");
      out.write("            color: #a0aec0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .has-icon .form-control {\r\n");
      out.write("            border-radius: 0 12px 12px 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-save {\r\n");
      out.write("            background: var(--primary-color);\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            margin-top: 1.5rem;\r\n");
      out.write("            transition: 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-save:hover {\r\n");
      out.write("            background: #3f37c9;\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 5px 15px rgba(67, 97, 238, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-back {\r\n");
      out.write("            color: #718096;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("            transition: 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-back:hover { color: var(--primary-color); }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container py-5\">\r\n");
      out.write("    <div class=\"row justify-content-center\">\r\n");
      out.write("        <div class=\"col-lg-8\">\r\n");
      out.write("            \r\n");
      out.write("            <!-- Botón Volver -->\r\n");
      out.write("            <a href=\"listarRodado\" class=\"btn-back\">\r\n");
      out.write("                <i class=\"fa-solid fa-arrow-left me-2\"></i> Volver al listado\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-card\">\r\n");
      out.write("                <div class=\"form-header\">\r\n");
      out.write("                    <i class=\"fa-solid fa-car-side fa-3x mb-3\"></i>\r\n");
      out.write("                    <h2 class=\"fw-bold mb-0\">Registrar Vehículo</h2>\r\n");
      out.write("                    <p class=\"mb-0 opacity-75\">Completa los datos técnicos del rodado</p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-body\">\r\n");
      out.write("                    <form class=\"form-crear-rodado\" action=\"");
      out.print( request.getContextPath() );
      out.write("/crearRodado\" method=\"post\">\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <!-- Patente -->\r\n");
      out.write("                            <div class=\"col-md-6 mb-4\">\r\n");
      out.write("                                <label for=\"patente\" class=\"form-label\">Patente</label>\r\n");
      out.write("                                <div class=\"input-group has-icon\">\r\n");
      out.write("                                    <span class=\"input-group-text\"><i class=\"fa-solid fa-id-card\"></i></span>\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" id=\"patente\" name=\"patente\" placeholder=\"Ej: ABC 123\" required>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Chasis -->\r\n");
      out.write("                            <div class=\"col-md-6 mb-4\">\r\n");
      out.write("                                <label for=\"chasis\" class=\"form-label\">Número de Chasis</label>\r\n");
      out.write("                                <div class=\"input-group has-icon\">\r\n");
      out.write("                                    <span class=\"input-group-text\"><i class=\"fa-solid fa-barcode\"></i></span>\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" id=\"chasis\" name=\"chasis\" placeholder=\"Nro de bastidor\" required>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Color -->\r\n");
      out.write("                            <div class=\"col-md-4 mb-4\">\r\n");
      out.write("                                <label for=\"color\" class=\"form-label\">Color</label>\r\n");
      out.write("                                <div class=\"input-group has-icon\">\r\n");
      out.write("                                    <span class=\"input-group-text\"><i class=\"fa-solid fa-palette\"></i></span>\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" id=\"color\" name=\"color\" placeholder=\"Ej: Azul\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Caja -->\r\n");
      out.write("                            <div class=\"col-md-4 mb-4\">\r\n");
      out.write("                                <label for=\"caja\" class=\"form-label\">Tipo de Caja</label>\r\n");
      out.write("                                <select class=\"form-select\" id=\"caja\" name=\"caja\">\r\n");
      out.write("                                    <option value=\"MANUAL\">Manual</option>\r\n");
      out.write("                                    <option value=\"AUTOMATICO\">Automática</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Motor -->\r\n");
      out.write("                            <div class=\"col-md-4 mb-4\">\r\n");
      out.write("                                <label for=\"motor\" class=\"form-label\">Motor</label>\r\n");
      out.write("                                <select class=\"form-select\" id=\"motor\" name=\"motor\">\r\n");
      out.write("                                    <option value=\"DIESEL\">Diesel</option>\r\n");
      out.write("                                    <option value=\"HIBRIDO\">Híbrido</option>\r\n");
      out.write("                                    <option value=\"ELECTRICO\">Eléctrico</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Estado -->\r\n");
      out.write("                            <div class=\"col-md-4 mb-4\">\r\n");
      out.write("                                <label for=\"TipoEstado\" class=\"form-label\">Estado</label>\r\n");
      out.write("                                <select class=\"form-select\" id=\"TipoEstado\" name=\"TipoEstado\">\r\n");
      out.write("                                    <option value=\"NUEVO\">Nuevo</option>\r\n");
      out.write("                                    <option value=\"USADO\">Usado</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Consumo -->\r\n");
      out.write("                            <div class=\"col-md-4 mb-4\">\r\n");
      out.write("                                <label for=\"TipoConsumo\" class=\"form-label\">Consumo</label>\r\n");
      out.write("                                <select class=\"form-select\" id=\"TipoConsumo\" name=\"TipoConsumo\">\r\n");
      out.write("                                    <option value=\"BAJO\">Bajo</option>\r\n");
      out.write("                                    <option value=\"MEDIO\">Medio</option>\r\n");
      out.write("                                    <option value=\"ALTO\">Alto</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Puertas -->\r\n");
      out.write("                            <div class=\"col-md-4 mb-4\">\r\n");
      out.write("                                <label for=\"puertas\" class=\"form-label\">Puertas</label>\r\n");
      out.write("                                <select class=\"form-select\" id=\"puertas\" name=\"puertas\">\r\n");
      out.write("                                    <option value=\"DOS\">2 Puertas</option>\r\n");
      out.write("                                    <option value=\"TRES\">3 Puertas</option>\r\n");
      out.write("                                    <option value=\"CUATRO\">4 Puertas</option>\r\n");
      out.write("                                    <option value=\"CINCO\">5 Puertas</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Categoría -->\r\n");
      out.write("                            <div class=\"col-md-12 mb-4\">\r\n");
      out.write("                                <label for=\"TipoRodado\" class=\"form-label\">Categoría del Vehículo</label>\r\n");
      out.write("                                <div class=\"input-group has-icon\">\r\n");
      out.write("                                    <span class=\"input-group-text\"><i class=\"fa-solid fa-truck-pickup\"></i></span>\r\n");
      out.write("                                    <select class=\"form-select\" id=\"TipoRodado\" name=\"TipoRodado\">\r\n");
      out.write("                                        <option value=\"AUTO\">Auto</option>\r\n");
      out.write("                                        <option value=\"CAMIONETA\">Camioneta</option>\r\n");
      out.write("                                        <option value=\"MOTO\">Moto</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary btn-save text-white shadow-sm\">\r\n");
      out.write("                            <i class=\"fa-solid fa-cloud-arrow-up me-2\"></i> Guardar Registro\r\n");
      out.write("                        </button>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"mt-4\">\r\n");
      out.write("                            ");
 if ("success".equals(request.getParameter("status"))) { 
      out.write("\r\n");
      out.write("                                <div class=\"alert alert-success border-0 rounded-4 shadow-sm d-flex align-items-center\">\r\n");
      out.write("                                    <i class=\"fa-solid fa-circle-check fs-4 me-3\"></i>\r\n");
      out.write("                                    <div>¡Rodado guardado con éxito!</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            ");
 } else if ("error".equals(request.getParameter("status"))) { 
      out.write("\r\n");
      out.write("                                <div class=\"alert alert-danger border-0 rounded-4 shadow-sm d-flex align-items-center\">\r\n");
      out.write("                                    <i class=\"fa-solid fa-circle-exclamation fs-4 me-3\"></i>\r\n");
      out.write("                                    <div>Hubo un error. Revisa los datos ingresados.</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
